### ISSUE TITLE
[action] argocd:create reports -> InvalidSpecError: repository not accessible: repositories not accessible

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/my-backstage-templates#2]
## Issue

```
12024-01-26T10:42:59.000Z Beginning step Create ArgoCD Resources22024-01-26T10:43:01.000Z 
Error: Error creating argo app: 
application spec for my-quarkus-app-bootstrap is invalid: 
InvalidSpecError: repository not accessible: repositories not accessible: 
&Repository{
Repo: "https://github.com/ch007m/toto.git, 
Type: "", 
Name: "", 
Project: ""}: 
repo client error while testing repository: 
rpc error: code = Unknown desc = error testing repository connectivity: 
authentication required at ArgoService.createArgoApplication 
(/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:379:13)4    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)5    at async ArgoService.createArgoResources (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:689:5)6    
at async Object.handler (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:1190:7)7    
at async NunjucksWorkflowRunner.executeStep (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6692:9)8    
at async NunjucksWorkflowRunner.execute (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6765:9)9    at async TaskWorker.runOneTask (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6987:26)10    at async run (/opt/app-root/src/node_modules/p-queue/dist/index.js:163:29)
```

**Comment by cmoulliard** [comment]
This problems occurs if the github repository created is `private` and not `public`
